### PR TITLE
Current Limiting (Intake)

### PR DESCRIPTION
**Pull request by roshanr10**
Closes #51

### CODE REVIEW

**Comment by roshanr10** [comment]
revised changes, please review and merge AFTER #52 has been merged into testing as the changes have already been pulled from that into this branch.

**Comment by roshanr10** [comment]
Yeah, I would generally agree with you on not merging other code, however, the code cleanup PR is blocking, and could potentially lead to merge conflicts later on. Thus, I preemptively fixed them in this PR. Hopefully, once that PR is in, this will seem a lot clearer.

The isolated changes can be seen here: https://github.com/FRCteam4909/2019-Deep-Space/compare/code-cleanup...current-limiting

**Comment by derrell** [comment]
At line 18 shown here https://github.com/FRCteam4909/2019-Deep-Space/compare/code-cleanup...current-limiting#diff-f02f273c6a99e5b8a84ef39cba03dd90R18... Is current limiting the only way indication of finished? That seems a dangerous way to determine it. No sensor?

**Comment by roshanr10** [comment]
Yeah, that was something to discuss/test once we have the completed mechanism.

Having a sensor trip as soon as the ball as in may prevent it from coming entirely within the intake as desired. We need to see if a time delay is required after IR detection, or if the current limit and driver feedback is sufficient. This is very dependent on the actual robot itself.

**Pull request merged**
