### PR TITLE
WIP: Initial cut at a user interface

### PR DESCRIPTION
**Pull request by derrell**
The `server` directory demonstrates what needs to go into the robot code.
The user interface for the Operator Console is in the `operator` directory. 

If you want to look at the user interface code, browse to `operator/source/class/operator/`. The `Application.js` class provides the main entry point.

We can likely generate a far more usable interface with this than with SmartDashboard, at the expense of additional development tools required for this. This uses a JavaScript framework called `qooxdoo`. I'd be glad to assist anyone interested in preparing the development environment for this. It's trivial on Linux; should be similarly easy on Mac, and known possible on Windows but I'd have to figure out how to do it.

This is a WIP PR, not to be merged with `testing` at this time. It has not yet been tested in/with the robot.

### CODE REVIEW

**Comment by roshanr10** [comment]
I'd like to take a look, but I'm unsure how to get `Application.js` running (qx is not defined if run as a node script) – is this intended to be the backend server for the operator GUI? I'd appreciate if you could help me get the dev. environment up and running

I tried looking at `index.html` but didn't have any luck with that either

**Comment by derrell** [comment]
I updated the top-level README.md to include usage instructions. See https://github.com/FRCteam4909/2019-Deep-Space/tree/gui/gui

**Comment by roshanr10** [comment]
Thanks, just looked at the client, seems like a good base... we'll have to look more into this.

Did you see my response in #60? FRCDashboard, not to be confused with SmartDashboard, can function in a similar fashion and builds upon existing NT code. This could help us if something were to go wrong in a competition setting, as CSAs are required to know the default code bases, but not custom code like this.

FRCDashboard also has a lot of examples of SVG inputs, that way it's a lot more intuitive for the operator to use– I could probably make some mockups in illustrator if we go that route. 

Another thing to consider is going that route would allow us to fall back to SmartDashboard as needed, with no loss in functionality. Perhaps, the interface might be aesthetically lacking, but it'll still be functional.

**Comment by derrell** [comment]
Yup, I responded to #60. Let's see what we have time to improve when all of the required stuff is complete.

**Comment by roshanr10** [comment]
Based on earlier discussion to got the NetworkTables route with FRCDashboard, I'm closing this for now.

I appreciate all of the effort put into making this, and we can reopen/take components from this in the future if we want to.

**Pull request closed without merging**
